# Numpy Array

In [59]:
import numpy as np 

In [60]:
arr=np.arange(1000000)

In [61]:
pythlist=list(range(1000000))


In [62]:
%time for _ in range(10): [item*3 for item in pythlist]

CPU times: total: 594 ms
Wall time: 582 ms


In [63]:
%time  for _ in range(10): arr=arr*3

CPU times: total: 15.6 ms
Wall time: 22 ms


 construction of numpy array

In [64]:
np.array([3,5,6,7,8,9])


array([3, 5, 6, 7, 8, 9])

Basic Numpy and slicing

In [65]:
arr1=np.array([2,3,4,5])
print(arr1)
print(type(arr1))

[2 3 4 5]
<class 'numpy.ndarray'>


In [66]:
print(arr1.shape)

(4,)


In [67]:
print(arr1.dtype)

int32


In [68]:
arr2=np.array([[3,2,4.8,3,5],[3,1,3,4,5]])
print(arr2.dtype)

float64


In [69]:
np.zeros((4,6))
 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [70]:
np.zeros((4,60)).dtype


dtype('float64')

In [71]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [72]:
arr2*arr2

array([[ 9.  ,  4.  , 23.04,  9.  , 25.  ],
       [ 9.  ,  1.  ,  9.  , 16.  , 25.  ]])

In [73]:
arr2+arr2

array([[ 6. ,  4. ,  9.6,  6. , 10. ],
       [ 6. ,  2. ,  6. ,  8. , 10. ]])

In [74]:
arr2-arr2


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
arr2/arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
arr1**arr1

array([   4,   27,  256, 3125])

In [77]:
1/arr1

array([0.5       , 0.33333333, 0.25      , 0.2       ])

In [78]:
arr1.shape

(4,)

In [79]:
arr1.dtype

dtype('int32')

In [80]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

## Slicing

In [81]:
arr1

array([2, 3, 4, 5])

In [82]:
arr=arr1[2:4]

print(arr)
here arr is view of arr1

In [83]:
arr[0]=9

In [84]:
arr1

array([2, 3, 9, 5])

In [85]:
arr=arr1[2:4].copy()
arr[0]=5
print(arr1)

[2 3 9 5]


In [86]:
arr2

array([[3. , 2. , 4.8, 3. , 5. ],
       [3. , 1. , 3. , 4. , 5. ]])

In [87]:
arr2[0,3]

3.0

# Axis 0 is Column wise  and Axis 1 is row wise

In [88]:
arr1=np.array([[1,2,3],[2,3,4]])

In [89]:
arr1.sum(axis=1)

array([6, 9])

In [90]:
arr1.sum(axis=0)

array([3, 5, 7])

In [91]:
arr2=np.array([[9,7,8],[8,1,9]])

In [92]:
arr1.dot(np.transpose(arr2))

array([[47, 37],
       [71, 55]])

In [93]:
arr1.dot(arr2.transpose())

array([[47, 37],
       [71, 55]])

In [94]:
np.dot(arr1,arr2.transpose())

array([[47, 37],
       [71, 55]])

# sorting


In [95]:
arr2.sort()

In [96]:
arr2

array([[7, 8, 9],
       [1, 8, 9]])

In [97]:
arr2.sort(axis=0)

In [98]:
arr2

array([[1, 8, 9],
       [7, 8, 9]])

In [99]:
arr2.sort(axis=1)

In [100]:
arr2

array([[1, 8, 9],
       [7, 8, 9]])

In [101]:
np.sort(arr2,axis=0,kind='mergsort')

array([[1, 8, 9],
       [7, 8, 9]])

Numpy arange , argsort

In [102]:
arr1=np.arange(6)

In [103]:
arr1

array([0, 1, 2, 3, 4, 5])

In [104]:
b=np.array([1,2,3,4,5,5,6,2,4,5,6,8,4,4,5,2,22,2,6,23,34,5,66,4])

In [105]:
b.shape

(24,)

In [106]:
# b=b.reshape(3,8)

In [107]:
b

array([ 1,  2,  3,  4,  5,  5,  6,  2,  4,  5,  6,  8,  4,  4,  5,  2, 22,
        2,  6, 23, 34,  5, 66,  4])

In [108]:
np.argsort(b)

array([ 0,  1, 17, 15,  7,  2, 13, 12, 23,  3,  8,  9,  5, 14,  4, 21, 10,
        6, 18, 11, 16, 19, 20, 22], dtype=int64)

In [109]:
np.argmin(b)

0

In [110]:
np.argmax(b)

22

In [111]:
b=b.reshape(3,8)

In [112]:
b

array([[ 1,  2,  3,  4,  5,  5,  6,  2],
       [ 4,  5,  6,  8,  4,  4,  5,  2],
       [22,  2,  6, 23, 34,  5, 66,  4]])

In [113]:
np.argsort(b)

array([[0, 1, 7, 2, 3, 4, 5, 6],
       [7, 0, 4, 5, 1, 6, 2, 3],
       [1, 7, 5, 2, 0, 3, 4, 6]], dtype=int64)

In [114]:
np.argsort(b,axis=0)

array([[0, 0, 0, 0, 1, 1, 1, 0],
       [1, 2, 1, 1, 0, 0, 0, 1],
       [2, 1, 2, 2, 2, 2, 2, 2]], dtype=int64)

In [115]:
np.argsort(b,axis=1)

array([[0, 1, 7, 2, 3, 4, 5, 6],
       [7, 0, 4, 5, 1, 6, 2, 3],
       [1, 7, 5, 2, 0, 3, 4, 6]], dtype=int64)

# Numpy tutorial

Numpy is Python library.
Numpy is used for working with arrays.
Numpy is short for "Numerical Python".

In [116]:
# create a numpy
import numpy as np 
arr=np.array([1,3,4,5,6])
print(arr)
print(type(arr))

[1 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
#Numpy is 50x faster than traditional Python list


In [117]:
# to get version of numpy 
print(np.__version__)
        
        

1.22.3


In [ ]:
# create a NumPy ndarray object by using the array() function.


In [119]:
arr_0=np.array(0)
print(arr_0)

0


In [122]:
arr_1=np.array([1,2,3,4])
print(arr_1)

[1 2 3 4]


In [124]:
arr_2=np.array([[2,3,4],[5,6,7]])
print(arr_2)

[[2 3 4]
 [5 6 7]]


In [127]:
arr_3=np.array([[[3,4,5],[3,0,8]],[[3,9,5],[7,5,4]]])
print(arr_3)

[[[3 4 5]
  [3 0 8]]

 [[3 9 5]
  [7 5 4]]]


In [129]:
# to check dimension
print(arr_0.ndim)
print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)

0
1
2
3


In [133]:
# create a dimension of higher dimension
arr_h=np.array([3,4,5,6,7],ndmin=5)
print(arr_h,arr_h.ndim,sep='\n')


[[[[[3 4 5 6 7]]]]]
5


In [136]:
# Access Array Indexing for 1 dimension
arr=np.array([3,4,5,6])
print(arr[0])

3


In [137]:
# Access Array Indexing for  2-d array
arr=np.array([[2,3,4,5],[4,6,7,8]])
# Access 1st row and 2nd column element
print(arr[0,1])

3


In [139]:
# Access 3-d Arrays
arr=np.array([[[1,2,3],[4,5,6]],[[2,3,5],[1,9,0]]])
print(arr[0,0,0])

1


In [140]:
# Numpy array Slicing 


In [142]:
# for 1d array
arr=np.array([3,4,5,6])
print(arr[0:2])

[3 4]


In [143]:
print(arr[2:])

[5 6]


In [146]:
print(arr[-3:-1])

[4 5]


In [154]:
print(arr[-3:3])

[4 5]


In [155]:
print(arr[:4])

[3 4 5 6]


In [156]:
# Negative slicing

In [157]:
print(arr[:-1])

[3 4 5]


In [159]:
print(arr[-1::-1])

[6 5 4 3]


In [160]:
# slicing 2d array


In [161]:
arr=np.array([[2,3,4,5],[4,6,7,8]])


In [165]:
print(arr[0:,2:4])

[[4 5]
 [7 8]]


In [166]:
print(arr[0,2:4])

[4 5]


In [167]:
print(arr.dtype)

int32


In [168]:
# Creating Arrays with a defined Data Type

In [171]:
arr=np.array([2,3,4,5,6],dtype='S')
print(arr)

[b'2' b'3' b'4' b'5' b'6']


In [173]:
# Differnce between copy and view
'''Main differnce between a copy and a view of an array is that the copy is anew
array, and the view of the original array'''

'''The copy owns the data and any changes made to the copy will not affect the original array, and 
original array, any changes made to the original array eill not affect the view'''

'''the view does not own the data and any changes made to the view will affect the original array, 
and any changes made to the original array will affect the view'''


'the view does not own the data and any changes made to the view will affect the original array, \nand any changes made to the original array will affect the view'

In [178]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)
print(x.base)

[42  2  3  4  5]
[1 2 3 4 5]
None


In [177]:
x=arr.view()
arr[0]=8
print(arr)
print(x)
print(x.base)

[8 2 3 4 5]
[8 2 3 4 5]
[8 2 3 4 5]


In [179]:
print(arr.shape)

(5,)


In [182]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(4,2)
print(newarr)
print(newarr.base)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6 7 8]


In [181]:
# print(arr.reshape(3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

In [183]:
# unknnown dimension
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [185]:
# flattering the arrays
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


In [187]:
# Iterating Arrays 
arr=np.array([1,2,3])
for x in  arr: 
    print(x)

1
2
3


In [188]:
# iterarting 2 d arrays
arr=np.array([[3,4],[4,5],[5,7]])
for x in arr:
    print(x)

[3 4]
[4 5]
[5 7]


In [189]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [190]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [192]:
arr1=np.array([2,3,4,5])
arr2=np.array([1,9,6,7])
arr=np.concatenate((arr1,arr2))
print(arr)

[2 3 4 5 1 9 6 7]


In [193]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [195]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [196]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
